import { Listing } from './types';

export const mockListings: Listing[] = [
  // 25평형
  {
    listingId: 'L001',
    tradeType: '매매',
    confirmedDate: '04.07',
    complexName: '화서역푸르지오더에듀포레',
    areaTypeRaw: '85/59.9',
    supplyArea: 85,
    exclusiveArea: 59.9,
    priceText: '66,800',
    priceValue: 66800,
    buildingNo: '101동',
    floorRaw: '저/20',
    agencyName: '푸르지오뱅크',
    description: '남향, 시원한 조망권, 초중고 인접',
    areaGroup: '25평형',
  },
  {
    listingId: 'L002', // 중복 매물 테스트 (L001과 동일)
    tradeType: '매매',
    confirmedDate: '04.06',
    complexName: '화서역푸르지오더에듀포레',
    areaTypeRaw: '85/59.9',
    supplyArea: 85,
    exclusiveArea: 59.9,
    priceText: '66,800',
    priceValue: 66800,
    buildingNo: '101동',
    floorRaw: '저/20',
    agencyName: '친구부동산',
    description: '급매, 남향, 상태 최상',
    areaGroup: '25평형',
  },
  {
    listingId: 'L003',
    tradeType: '매매',
    confirmedDate: '04.07',
    complexName: '화서역푸르지오더에듀포레',
    areaTypeRaw: '85A/59.9',
    supplyArea: 85,
    exclusiveArea: 59.9,
    priceText: '70,000',
    priceValue: 70000,
    buildingNo: '102동',
    floorRaw: '고/20',
    agencyName: '에듀포레공인',
    description: '로얄층, 올수리, 입주협의',
    areaGroup: '25평형',
  },

  // 33평형
  {
    listingId: 'L004',
    tradeType: '매매',
    confirmedDate: '04.07',
    complexName: '화서역푸르지오더에듀포레',
    areaTypeRaw: '110E/84.7',
    supplyArea: 110,
    exclusiveArea: 84.7,
    priceText: '82,000',
    priceValue: 82000,
    buildingNo: '132동',
    floorRaw: '저/25',
    agencyName: '스타부동산',
    description: '상가초교앞 선호동, 채광 좋음',
    areaGroup: '33평형',
  },
  {
    listingId: 'L005', // 타입 다름 (합치면 안됨)
    tradeType: '매매',
    confirmedDate: '04.05',
    complexName: '화서역푸르지오더에듀포레',
    areaTypeRaw: '110C/84.7',
    supplyArea: 110,
    exclusiveArea: 84.7,
    priceText: '82,000',
    priceValue: 82000,
    buildingNo: '132동',
    floorRaw: '저/25',
    agencyName: '스타부동산',
    description: 'C타입 급매, 조망 우수',
    areaGroup: '33평형',
  },
  {
    listingId: 'L006',
    tradeType: '매매',
    confirmedDate: '04.07',
    complexName: '화서역푸르지오더에듀포레',
    areaTypeRaw: '111A/84.9',
    supplyArea: 111,
    exclusiveArea: 84.9,
    priceText: '78,000',
    priceValue: 78000,
    buildingNo: '106동',
    floorRaw: '저/25',
    agencyName: '친구부동산',
    description: '상가초교앞 선호동, 채광 좋음',
    areaGroup: '33평형',
  },
  {
    listingId: 'L007', // 층 표기 다름 (합치면 안됨)
    tradeType: '매매',
    confirmedDate: '04.07',
    complexName: '화서역푸르지오더에듀포레',
    areaTypeRaw: '111A/84.9',
    supplyArea: 111,
    exclusiveArea: 84.9,
    priceText: '78,000',
    priceValue: 78000,
    buildingNo: '106동',
    floorRaw: '3/25',
    agencyName: '베스트공인',
    description: '필로티 3층, 층간소음 걱정없음',
    areaGroup: '33평형',
  },

  // 42평형
  {
    listingId: 'L008',
    tradeType: '매매',
    confirmedDate: '04.06',
    complexName: '화서역푸르지오더에듀포레',
    areaTypeRaw: '141B/113',
    supplyArea: 141,
    exclusiveArea: 113,
    priceText: '85,000',
    priceValue: 85000,
    buildingNo: '121동',
    floorRaw: '저/30',
    agencyName: '푸르지오뱅크',
    description: '남향, 시원한 조망권, 초중고 인접',
    areaGroup: '42평형',
  },
  {
    listingId: 'L009', // 타입 다름 (합치면 안됨)
    tradeType: '매매',
    confirmedDate: '04.07',
    complexName: '화서역푸르지오더에듀포레',
    areaTypeRaw: '141A/113.7',
    supplyArea: 141,
    exclusiveArea: 113.7,
    priceText: '85,000',
    priceValue: 85000,
    buildingNo: '121동',
    floorRaw: '저/30',
    agencyName: '푸르지오뱅크',
    description: 'A타입 판상형, 채광 우수',
    areaGroup: '42평형',
  },

  // 48평형
  {
    listingId: 'L010',
    tradeType: '매매',
    confirmedDate: '04.07',
    complexName: '화서역푸르지오더에듀포레',
    areaTypeRaw: '160C/129.6',
    supplyArea: 160,
    exclusiveArea: 129.6,
    priceText: '90,000',
    priceValue: 90000,
    buildingNo: '130동',
    floorRaw: '5/15',
    agencyName: '탑공인중개사',
    description: '정원뷰, 조용하고 쾌적함',
    areaGroup: '48평형',
  },
  {
    listingId: 'L011', // 타입 다름 (합치면 안됨)
    tradeType: '매매',
    confirmedDate: '04.06',
    complexName: '화서역푸르지오더에듀포레',
    areaTypeRaw: '161A/129.5',
    supplyArea: 161,
    exclusiveArea: 129.5,
    priceText: '90,000',
    priceValue: 90000,
    buildingNo: '130동',
    floorRaw: '5/15',
    agencyName: '탑공인중개사',
    description: 'A타입 정남향, 일조량 풍부',
    areaGroup: '48평형',
  },

  // 55평형
  {
    listingId: 'L012',
    tradeType: '매매',
    confirmedDate: '04.07',
    complexName: '화서역푸르지오더에듀포레',
    areaTypeRaw: '182/148.5',
    supplyArea: 182,
    exclusiveArea: 148.5,
    priceText: '100,000',
    priceValue: 100000,
    buildingNo: '115동',
    floorRaw: '중/20',
    agencyName: 'VIP부동산',
    description: '펜트하우스급 조망, 특올수리',
    areaGroup: '55평형',
  },
];
